### ISSUE TITLE
Les imports se font mal

### ISSUE THREAD

**Issue by marota** [GoubetClem/VAE#1]
A partir de la cellule 21:
"import importlib

sys.path.append(path_second_folder+'/src')

import .models, .loss_class, .params_class, .AE_blocks,metrics
from models import *"

Pour Vérifier que ça se passe bien, lancer binder et éxécuter tout le notebook

**Comment by marota** [comment]
@laure-crochepierre avais-tu une version qui tourne avec les bons imports? Si oui, peux-tu la partager ?

**Comment by laure-crochepierre** [comment]
J'ai du modifier les variables dans la cellule située au dessus 
``` 
path_second_folder = "/home/???/VAE/"
save_path = "/home/???/VAE/"
```
Est-ce que l'import fonctionne ? 

Dans l'exemple que tu donnes au dessus tu as aussi un point avant chaque import (```.model``` par exemple)
